nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.19.vcf  --everything -o /halde/wholeGenome/chr19.vep > vep19.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.18.vcf  --everything -o /halde/wholeGenome/chr18.vep > vep18.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.17.vcf  --everything -o /halde/wholeGenome/chr17.vep > vep17.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.16.vcf  --everything -o /halde/wholeGenome/chr16.vep > vep16.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.15.vcf  --everything -o /halde/wholeGenome/chr15.vep > vep15.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.14.vcf  --everything -o /halde/wholeGenome/chr14.vep > vep14.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.13.vcf  --everything -o /halde/wholeGenome/chr13.vep > vep13.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.12.vcf  --everything -o /halde/wholeGenome/chr12.vep > vep12.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.11.vcf  --everything -o /halde/wholeGenome/chr11.vep > vep11.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.10.vcf  --everything -o /halde/wholeGenome/chr10.vep > vep10.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.9.vcf  --everything -o /halde/wholeGenome/chr9.vep > vep9.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.8.vcf  --everything -o /halde/wholeGenome/chr8.vep > vep8.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.7.vcf  --everything -o /halde/wholeGenome/chr7.vep > vep7.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.6.vcf  --everything -o /halde/wholeGenome/chr6.vep > vep6.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.5.vcf  --everything -o /halde/wholeGenome/chr5.vep > vep5.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.4.vcf  --everything -o /halde/wholeGenome/chr4.vep > vep4.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.3.vcf  --everything -o /halde/wholeGenome/chr3.vep > vep3.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.2.vcf  --everything -o /halde/wholeGenome/chr2.vep > vep2.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.1.vcf  --everything -o /halde/wholeGenome/chr1.vep > vep1.log 2>&1 &
nohup vep --species mus_musculus --offline -i /halde/wholeGenome/Founders.snps.X.vcf  --everything -o /halde/wholeGenome/chrX.vep > vepX.log 2>&1 &
